apiVersion: v1
kind: Template
metadata:
  name: influxdb
parameters:
- name: STORAGE_SIZE
  value: 10Gi
  description: The size of the persistent storage for Influxdb
- description: The admin password
  name: ADMIN_PASSWORD
  generate: expression
  from: "[a-zA-Z0-9]{43}"
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: influxdb-data
    labels:
      app: influxdb
  spec:
    storageClassName: ceph-dyn-datahub
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${STORAGE_SIZE}
- apiVersion: v1
  kind: Secret
  metadata:
    name: admin-password
    labels:
      app: influxdb
  stringData:
    admin_password: "${ADMIN_PASSWORD}"
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: influxdb
    name: influxdb
  spec:
    ports:
    - name: api-http
      port: 8086
      protocol: TCP
      targetPort: 8086
    - name: api-udp
      port: 8087
      protocol: UDP
      targetPort: 8087
    - name: admin-http
      port: 8083
      protocol: TCP
      targetPort: 8083
    selector:
      app: influxdb
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    name: influxdb
    namespace: influx
    labels:
      app: influxdb
  spec:
    port:
      targetPort: api-http
    to:
      kind: Service
      name: influxdb
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: influxdb
  spec:
    replicas: 1
    selector:
      app: influxdb
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      type: Recreate
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: influxdb
      spec:
        containers:
        - image: influxdb
          env:
            - name: INFLUXDB_DB
              value: 'prometheus'
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: 'true'
            - name: INFLUXDB_ADMIN_USER
              value: 'admin'
            - name: INFLUXDB_ADMIN_PASSWORD
              value: "${ADMIN_PASSWORD}"
            - name: INFLUXDB_DATA_INDEX_VERSION
              value: "tsi1"
            - name: INFLUXDB_DATA_MAX_SERIES_PER_DATABASE
              value: '0'
            - name: INFLUXDB_DATA_MAX_VALUES_PER_TAG
              value: '0'
          imagePullPolicy: Always
          name: influxdb
          tag: 1.5.1
          ports:
          - containerPort: 8086
            protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 32Gi
            requests:
              cpu: '2'
              memory: 8Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/influxdb
            name: influxdb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data
    test: false
    triggers:
    - type: ConfigChange
